{
 "title": "Disturbances",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "selected_mountpoint",
    "label": "Mountpoint",
    "query": "SELECT sc.mountpoint\nFROM sourcetable_constants sc\nWHERE mountpoint IN (SELECT DISTINCT mountpoint FROM rtcm_packages)"
   },
   {
    "name": "signals_gps",
    "query": "SELECT DISTINCT sat_signal\nFROM gps_observations where mountpoint = '$selected_mountpoint' AND $__timeFilter(obs_epoch) ORDER BY sat_signal"
   },
   {
    "name": "signals_gal",
    "query": "SELECT DISTINCT sat_signal\nFROM galileo_observations where mountpoint = '$selected_mountpoint' AND $__timeFilter(obs_epoch) ORDER BY sat_signal"
   },
   {
    "name": "signals_glo",
    "query": "SELECT DISTINCT sat_signal\nFROM glonass_observations where mountpoint = '$selected_mountpoint' AND $__timeFilter(obs_epoch) ORDER BY sat_signal"
   },
   {
    "name": "signals_bds",
    "query": "SELECT DISTINCT sat_signal\nFROM bds_observations where mountpoint = '$selected_mountpoint' AND $__timeFilter(obs_epoch) ORDER BY sat_signal"
   }
  ]
 },
 "panels": [
  { "title": "Average Signal to Noise", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "GPS SNR",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroupAlias(obs_epoch,$__interval),\r\nAVG(CASE WHEN sat_signal = 'L1C' then obs_snr END) AS \"L1C\",\r\nAVG(CASE WHEN sat_signal = 'L1P' then obs_snr END) AS \"L1P\",\r\nAVG(CASE WHEN sat_signal = 'L1W' then obs_snr END) AS \"L1W\",\r\nAVG(CASE WHEN sat_signal = 'L1S' then obs_snr END) AS \"L1S\",\r\nAVG(CASE WHEN sat_signal = 'L1L' then obs_snr END) AS \"L1L\",\r\nAVG(CASE WHEN sat_signal = 'L1X' then obs_snr END) AS \"L1X\"\r\n,\r\nAVG(CASE WHEN sat_signal = 'L2C' then obs_snr END) AS \"L2C\",\r\nAVG(CASE WHEN sat_signal = 'L2P' then obs_snr END) AS \"L2P\",\r\nAVG(CASE WHEN sat_signal = 'L2W' then obs_snr END) AS \"L2W\",\r\nAVG(CASE WHEN sat_signal = 'L2S' then obs_snr END) AS \"L2S\",\r\nAVG(CASE WHEN sat_signal = 'L2L' then obs_snr END) AS \"L2L\",\r\nAVG(CASE WHEN sat_signal = 'L2X' then obs_snr END) AS \"L2X\"\r\n,\r\nAVG(CASE WHEN sat_signal = 'L5I' then obs_snr END) AS \"L5I\",\r\nAVG(CASE WHEN sat_signal = 'L5Q' then obs_snr END) AS \"L5Q\",\r\nAVG(CASE WHEN sat_signal = 'L5X' then obs_snr END) AS \"L5X\"\r\nFROM gps_observations where mountpoint = '$selected_mountpoint' AND $__timeFilter(obs_epoch) group by 1"
    }
   ]
  },
  {
   "title": "Glonass SNR",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroupAlias(obs_epoch,$__interval),\r\nAVG(CASE WHEN sat_signal = 'G1C' then obs_snr END) AS \"G1C\",\r\nAVG(CASE WHEN sat_signal = 'G1P' then obs_snr END) AS \"G1P\",\r\nAVG(CASE WHEN sat_signal = 'G2C' then obs_snr END) AS \"G2C\",\r\nAVG(CASE WHEN sat_signal = 'G2P' then obs_snr END) AS \"G2P\"\r\nFROM glonass_observations where mountpoint = '$selected_mountpoint' AND $__timeFilter(obs_epoch) group by 1"
    }
   ]
  },
  {
   "title": "Galileo SNR",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroupAlias(obs_epoch,$__interval),\r\nAVG(CASE WHEN sat_signal = 'E1C' then obs_snr END) AS \"E1C\",\r\nAVG(CASE WHEN sat_signal = 'E1A' then obs_snr END) AS \"E1A\",\r\nAVG(CASE WHEN sat_signal = 'E1B' then obs_snr END) AS \"E1B\",\r\nAVG(CASE WHEN sat_signal = 'E1X' then obs_snr END) AS \"E1X\",\r\nAVG(CASE WHEN sat_signal = 'E1Z' then obs_snr END) AS \"E1Z\",\r\n\r\nAVG(CASE WHEN sat_signal = 'E6C' then obs_snr END) AS \"E6C\",\r\nAVG(CASE WHEN sat_signal = 'E6A' then obs_snr END) AS \"E6A\",\r\nAVG(CASE WHEN sat_signal = 'E6B' then obs_snr END) AS \"E6B\",\r\nAVG(CASE WHEN sat_signal = 'E6X' then obs_snr END) AS \"E6X\",\r\nAVG(CASE WHEN sat_signal = 'E6Z' then obs_snr END) AS \"E6Z\",\r\n\r\nAVG(CASE WHEN sat_signal = 'E7I' then obs_snr END) AS \"E7I\",\r\nAVG(CASE WHEN sat_signal = 'E7Q' then obs_snr END) AS \"E7Q\",\r\nAVG(CASE WHEN sat_signal = 'E7X' then obs_snr END) AS \"E7X\",\r\n\r\nAVG(CASE WHEN sat_signal = 'E8I' then obs_snr END) AS \"E8I\",\r\nAVG(CASE WHEN sat_signal = 'E8Q' then obs_snr END) AS \"E8Q\",\r\nAVG(CASE WHEN sat_signal = 'E8X' then obs_snr END) AS \"E8X\",\r\n\r\nAVG(CASE WHEN sat_signal = 'E5I' then obs_snr END) AS \"E5I\",\r\nAVG(CASE WHEN sat_signal = 'E5Q' then obs_snr END) AS \"E5Q\",\r\nAVG(CASE WHEN sat_signal = 'E5X' then obs_snr END) AS \"E5X\"\r\nFROM galileo_observations where mountpoint = '$selected_mountpoint' AND $__timeFilter(obs_epoch) group by 1"
    }
   ]
  },
  {
   "title": "Beidou SNR",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroupAlias(obs_epoch,$__interval), \r\nAVG(CASE WHEN sat_signal = 'B2I' then obs_snr END) AS \"B2I\",\r\nAVG(CASE WHEN sat_signal = 'B2Q' then obs_snr END) AS \"B2Q\",\r\nAVG(CASE WHEN sat_signal = 'B2X' then obs_snr END) AS \"B2X\",\r\n\r\nAVG(CASE WHEN sat_signal = 'B6I' then obs_snr END) AS \"B6I\",\r\nAVG(CASE WHEN sat_signal = 'B6Q' then obs_snr END) AS \"B6Q\",\r\nAVG(CASE WHEN sat_signal = 'B6X' then obs_snr END) AS \"B6X\",\r\n\r\nAVG(CASE WHEN sat_signal = 'B7I' then obs_snr END) AS \"B7I\",\r\nAVG(CASE WHEN sat_signal = 'B7Q' then obs_snr END) AS \"B7Q\",\r\nAVG(CASE WHEN sat_signal = 'B7X' then obs_snr END) AS \"B7X\",\r\n\r\nAVG(CASE WHEN sat_signal = 'B5D' then obs_snr END) AS \"B5D\",\r\nAVG(CASE WHEN sat_signal = 'B5P' then obs_snr END) AS \"B5P\",\r\nAVG(CASE WHEN sat_signal = 'B5X' then obs_snr END) AS \"B5X\",\r\nAVG(CASE WHEN sat_signal = 'B7D' then obs_snr END) AS \"B7D\",\r\n\r\nAVG(CASE WHEN sat_signal = 'B1D' then obs_snr END) AS \"B1D\",\r\nAVG(CASE WHEN sat_signal = 'B1P' then obs_snr END) AS \"B1P\",\r\nAVG(CASE WHEN sat_signal = 'B1X' then obs_snr END) AS \"B1X\"\r\nFROM beidou_observations where mountpoint = '$selected_mountpoint' AND $__timeFilter(obs_epoch) group by 1"
    }
   ]
  }
 ]
}