{
 "title": "Inspector Gadget",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "countryCode",
    "label": "Country Code",
    "query": "SELECT DISTINCT countrycode\nFROM sourcetable_constants"
   },
   {
    "name": "UniqueMountpoints",
    "label": "Unique Mountpoints",
    "query": "SELECT DISTINCT rtc.mountpoint\nFROM rtcm_packages rtc\nJOIN sourcetable_constants stc ON rtc.mountpoint = stc.mountpoint\nWHERE stc.countrycode = $countryCode"
   },
   {
    "name": "ObservationTable",
    "label": "Constellation",
    "query": "gps_observations, beidou_observations, galileo_observations, glonass_observations, sbas_observations, qzss_observations"
   },
   {
    "name": "UniqueSatellites",
    "label": "Unique Satellites",
    "query": "SELECT DISTINCT sat_id\nFROM $ObservationTable"
   },
   {
    "name": "UniqueSignals",
    "label": "Unique Signals",
    "query": "SELECT DISTINCT sat_signal\nFROM $ObservationTable"
   },
   { "name": "GPSleap", "label": "GPS leapseconds", "query": "18" },
   { "name": "GALleap", "label": "Galileo Leap second", "query": "18" },
   { "name": "GLOleap", "label": "GLONASS leap seconds", "query": "0" },
   { "name": "QZZleap", "label": "QZZS leap seconds", "query": "18" },
   { "name": "BEIleap", "label": "BEIDEU leap seconds", "query": "4" }
  ]
 },
 "panels": [
  { "title": "Inspector Gadget Guide", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "# <img align=\"left\" src=\"https://pdlionunlimited.files.wordpress.com/2021/06/inspector-gadget.png\" width=\"150\" height=\"150\" style=\"float: right\" /> <center> Inspector Gadget <center>\nInspector Gadget is an easy-to-use grafana dashboard with the purpose of being able to quickly \ninspect the incoming MSM data at any mountpoint. The dashboard enables inspection of data received \nat any mountpoint from the respective satellite constellations GPS, Glonass, Galileo and Beidou. Furthermore, from each constellation it is possible to inspect data received from individual satellites and the individual signal types. The possible dropdown menu combinations are shown below\n\n1. **Unique Mountpoints** Mountpoints to select. Ordered alphebetically. Multi-select is possible.\n2. **Constellation** Which constellation to investigate data from. ordered alphebetically. Can only have one active at a time.\n3. **Unique Satellites** Satellites to select. Ordered alphebetically. Multi-select is possible.\n4. **Unique Singlas** Signal type to select. Ordered alphebetically. Multi-select is possible.\n\nSeveral dashboards are available in Inspector Gadget, with the potential to extended significantly. Current overview includes\n1. **Signal to Noise Ratio** Signal to noise ratio inspection.\n2. **Doppler data** Code data\n3. **Code Minus Phase Data** The difference between the received Code and Phase data. \n4. **Code Data** Code data.\n5. **Phase Data** Phase data.\n6. **Recent Mountpoint Statistics** Satellite and signal statistics for the chosen constellation in the last 30 minutes\n7. **Recent Satellite Statistics** Mountpoint and signal statistics for the chosen constellation in the last 30 minutes.\n8. **Satellite statistics** Time since satellite was last observed, and at which mountpoint it was last observed."
   }
  },
  { "title": "Basic GPS Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Signal to Noise ratio data",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT \n    obs_epoch AS \"time\", \n    mountpoint AS \"Mountpoint\", \n    sat_id AS \"Satellite\", \n    sat_signal AS \"Signal\", \n    obs_snr AS \"SNR\" \nFROM \n    $ObservationTable \nWHERE \n    mountpoint IN ($UniqueMountpoints) AND \n    sat_id IN ($UniqueSatellites) AND \n    sat_signal IN ($UniqueSignals) AND\n    obs_epoch BETWEEN $__timeFrom() AND $__timeTo()\nORDER BY \n    obs_epoch"
    }
   ]
  },
  {
   "title": "Doppler data",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "rawSql": "SELECT \n    obs_epoch AS \"time\", \n    mountpoint AS \"Mountpoint\", \n    sat_id AS \"Satellite\", \n    sat_signal AS \"Signal\", \n    obs_doppler AS \"Doppler\" \nFROM \n    $ObservationTable \nWHERE \n    mountpoint IN ($UniqueMountpoints) AND \n    sat_id IN ($UniqueSatellites) AND \n    sat_signal IN ($UniqueSignals) AND\n    obs_epoch BETWEEN $__timeFrom() AND $__timeTo()\nORDER BY \n    obs_epoch"
    }
   ]
  },
  {
   "title": "Code minus phase data",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "rawSql": "SELECT \n    obs_epoch AS \"time\", \n    mountpoint AS \"Mountpoint\", \n    sat_id AS \"Satellite\", \n    sat_signal AS \"Signal\", \n    obs_code - obs_phase AS \"Doppler\" \nFROM \n    $ObservationTable \nWHERE \n    mountpoint IN ($UniqueMountpoints) AND \n    sat_id IN ($UniqueSatellites) AND \n    sat_signal IN ($UniqueSignals) AND\n    obs_epoch BETWEEN $__timeFrom() AND $__timeTo()\nORDER BY \n    obs_epoch"
    }
   ]
  },
  {
   "title": "Code data",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "rawSql": "SELECT \n    obs_epoch AS \"time\", \n    mountpoint AS \"Mountpoint\", \n    sat_id AS \"Satellite\", \n    sat_signal AS \"Signal\", \n    obs_code AS \"Code\" \nFROM \n    $ObservationTable \nWHERE \n    mountpoint IN ($UniqueMountpoints) AND \n    sat_id IN ($UniqueSatellites) AND \n    sat_signal IN ($UniqueSignals) AND\n    obs_epoch BETWEEN $__timeFrom() AND $__timeTo()\nORDER BY \n    obs_epoch"
    }
   ]
  },
  {
   "title": "Phase data",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "rawSql": "SELECT \n    obs_epoch AS \"time\", \n    mountpoint AS \"Mountpoint\", \n    sat_id AS \"Satellite\", \n    sat_signal AS \"Signal\", \n    obs_phase AS \"Phase\" \nFROM \n    $ObservationTable \nWHERE \n    mountpoint IN ($UniqueMountpoints) AND \n    sat_id IN ($UniqueSatellites) AND \n    sat_signal IN ($UniqueSignals) AND\n    obs_epoch BETWEEN $__timeFrom() AND $__timeTo()\nORDER BY \n    obs_epoch"
    }
   ]
  },
  {
   "title": "Mountpoint statistics last 30 minutes",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  obs.mountpoint AS \"Mountpoint\",\r\n  stc.casterprovider AS \"Caster Provider\",\r\n  stc.countrycode AS \"Country Code\",\r\n  stc.receiver AS \"Receiver\",\r\n  string_agg(DISTINCT cast(obs.sat_signal as text), ', ') AS \"Satellite Signals\",\r\n  string_agg(DISTINCT cast(obs.sat_id as text), ', ') AS \"Observed Satellites\"\r\nFROM $ObservationTable obs\r\nJOIN sourcetable_constants stc ON obs.mountpoint = stc.mountpoint\r\nWHERE obs.obs_epoch >= NOW() - INTERVAL '30 minutes'\r\nGROUP BY obs.mountpoint, stc.casterprovider, stc.countrycode, stc.receiver\r\nORDER BY obs.mountpoint"
    }
   ]
  },
  {
   "title": "Satellite statistics last 30 minutes",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  cast(sat_id as text) AS \"Observed Satellites\",\r\n  string_agg(DISTINCT mountpoint, ', ') AS \"Mountpoints\",\r\n  string_agg(DISTINCT cast(sat_signal as text), ', ') AS \"Satellite Signals\"\r\nFROM $ObservationTable\r\nWHERE obs_epoch >= NOW() - INTERVAL '30 minutes'\r\nGROUP BY sat_id\r\nORDER BY sat_id"
    }
   ]
  },
  {
   "title": "Satellite statistics last 30 minutes",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 70 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  cast(sat_id as text) AS \"Observed Satellites\",\r\n  string_agg(DISTINCT mountpoint, ', ') AS \"Mountpoints\",\r\n  string_agg(DISTINCT cast(sat_signal as text), ', ') AS \"Satellite Signals\",\r\n  CONCAT(\r\n    ABS(EXTRACT(HOUR FROM age(NOW() + INTERVAL '1 second' * \r\n      CASE\r\n        WHEN '$ObservationTable' = 'gps_observations' THEN $GPSleap\r\n        WHEN '$ObservationTable' = 'glonass_observations' THEN $GLOleap\r\n        WHEN '$ObservationTable' = 'galileo_observations' THEN $GALleap\r\n        WHEN '$ObservationTable' = 'qzss_observations' THEN $QZZleap\r\n        WHEN '$ObservationTable' = 'beideu_observations' THEN $BEIleap\r\n        ELSE 0\r\n      END, MAX(obs_epoch)))), ' hours ',\r\n    ABS(EXTRACT(MINUTE FROM age(NOW() + INTERVAL '1 second' * \r\n      CASE\r\n        WHEN '$ObservationTable' = 'gps_observations' THEN $GPSleap\r\n        WHEN '$ObservationTable' = 'glonass_observations' THEN $GLOleap\r\n        WHEN '$ObservationTable' = 'galileo_observations' THEN $GALleap\r\n        WHEN '$ObservationTable' = 'qzss_observations' THEN $QZZleap\r\n        WHEN '$ObservationTable' = 'beideu_observations' THEN $BEIleap\r\n        ELSE 0\r\n      END, MAX(obs_epoch)))), ' minutes ',\r\n    ABS(EXTRACT(SECOND FROM age(NOW() + INTERVAL '1 second' * \r\n      CASE\r\n        WHEN '$ObservationTable' = 'gps_observations' THEN $GPSleap\r\n        WHEN '$ObservationTable' = 'glonass_observations' THEN $GLOleap\r\n        WHEN '$ObservationTable' = 'galileo_observations' THEN $GALleap\r\n        WHEN '$ObservationTable' = 'qzss_observations' THEN $QZZleap\r\n        WHEN '$ObservationTable' = 'beideu_observations' THEN $BEIleap\r\n        ELSE 0\r\n      END, MAX(obs_epoch)))), ' seconds'\r\n  ) AS \"Time Since Last Observation\"\r\nFROM $ObservationTable\r\nWHERE obs_epoch >= NOW() - INTERVAL '30 minutes'\r\nGROUP BY sat_id\r\nORDER BY sat_id"
    }
   ]
  }
 ]
}