{
 "title": "RTCM overview",
 "time": { "from": "2024-10-24T13:24:19.644Z", "to": "2024-10-24T13:41:57.934Z" },
 "templating": {
  "list": [
   { "name": "GPSleapseconds", "query": "18" },
   { "name": "GALleapseconds", "query": "18" },
   { "name": "GLOleapseconds", "query": "0" },
   { "name": "QZZSleapseconds", "query": "18" },
   { "name": "BEIleapseconds", "query": "4" },
   {
    "name": "data_gap_interval",
    "label": "Data gap interval",
    "query": "10s, 20s, 30s, 1m, 5m, 15m, 30m, 1h, 2h, 4h, 6h, 12h, 1d"
   }
  ]
 },
 "panels": [
  {
   "title": "Disconnected mountpoints",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT mountpoint, disconnect_time, reconnect_time, coalesce(reconnect_time, CURRENT_TIMESTAMP)-disconnect_time as duration FROM connection_logger WHERE $__timeFilter(disconnect_time) OR reconnect_time IS NULL OR \r\n$__timeFilter(reconnect_time) ORDER BY disconnect_time DESC"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Data flow [bytes/min]",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  mountpoint AS metric,\r\n  AVG(count_per_minute) AS \"avg_rtcm_sat_count\"\r\nFROM (\r\n  SELECT\r\n    mountpoint,\r\n    date_trunc('minute', receive_time) as minute,\r\n    SUM(rtcm_msg_size) AS count_per_minute\r\n  FROM rtcm_packages\r\n  WHERE\r\n    $__timeFilter(receive_time)\r\n  GROUP BY mountpoint, minute\r\n) subquery\r\nGROUP BY mountpoint\r\nORDER BY mountpoint"
    }
   ]
  },
  {
   "title": "Average Satellite Count [Sat/min]",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  mountpoint AS metric,\r\n  AVG(count_per_minute)/60 AS \"avg_rtcm_sat_count\"\r\nFROM (\r\n  SELECT\r\n    mountpoint,\r\n    date_trunc('minute', receive_time) as minute,\r\n    SUM(rtcm_sat_count) AS count_per_minute\r\n  FROM rtcm_packages\r\n  WHERE\r\n    $__timeFilter(receive_time)\r\n  GROUP BY mountpoint, minute\r\n) subquery\r\nGROUP BY mountpoint\r\nORDER BY mountpoint"
    }
   ]
  },
  {
   "title": "Time series data flow [bytes/min]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(receive_time,1m),\n  mountpoint AS metric,\n  SUM(rtcm_msg_size) AS \"rtcm_sat_count\"\nFROM rtcm_packages \nWHERE\n  $__timeFilter(receive_time)\nGROUP BY 1,2 \nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Time Series Average Satellite Count [Sat/min]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(receive_time,1m),\n  mountpoint AS metric,\n  SUM(rtcm_sat_count)/60 AS \"rtcm_sat_count\"\nFROM rtcm_packages \nWHERE\n $__timeFilter(receive_time)\nGROUP BY 1,2 \nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Data gaps",
   "type": "status-history",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroupAlias(receive_time,'10s'),\r\n  mountpoint AS metric,\r\n  COUNT(rtcm_obs_epoch) AS \"epoch_obs\"\r\nFROM rtcm_packages\r\nWHERE\r\n  $__timeFilter(receive_time) AND\r\n  rtcm_msg_type IN (1077, 1087, 1097, 1117, 1127) AND\r\n  rtcm_obs_epoch IS NOT NULL and\r\n  rtcm_sat_count != 0\r\nGROUP BY 1,2\r\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Data gaps",
   "type": "status-history",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroupAlias(receive_time,$data_gap_interval),\r\n  mountpoint AS metric,\r\n  COUNT(rtcm_obs_epoch) AS \"epoch_obs\"\r\nFROM rtcm_packages\r\nWHERE\r\n  $__timeFilter(receive_time) AND\r\n  rtcm_msg_type IN (1077, 1087, 1097, 1117, 1127) AND\r\n  rtcm_obs_epoch IS NOT NULL and\r\n  rtcm_sat_count != 0\r\nGROUP BY 1,2\r\nORDER BY 1,2"
    }
   ]
  },
  { "title": "Latency Stations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Average latency [ALL/ min / all stats]",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  DATE_TRUNC('minute', receive_time) AS time,\r\n  mountpoint AS metric,\r\n  AVG(MOD((EXTRACT(epoch FROM receive_time) + \r\n    CASE \r\n      WHEN rtcm_msg_type = 1077 THEN $GPSleapseconds\r\n      WHEN rtcm_msg_type = 1087 THEN $GLOleapseconds\r\n      WHEN rtcm_msg_type = 1097 THEN $GALleapseconds\r\n      WHEN rtcm_msg_type = 1117 THEN $QZZSleapseconds\r\n      WHEN rtcm_msg_type = 1127 THEN $BEIleapseconds\r\n      ELSE $GPSleapseconds\r\n    END)::NUMERIC(15,3),86400) - MOD((EXTRACT(epoch FROM rtcm_obs_epoch)),86400)) as value\r\nFROM rtcm_packages\r\nWHERE\r\n  $__timeFilter(receive_time) AND\r\n  rtcm_obs_epoch IS NOT NULL AND\r\n  rtcm_sat_count != 0\r\nGROUP BY 1,2\r\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Average latency [ALL/ min / all stats]",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 57 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  receive_time AS time,\r\n  mountpoint AS metric,\r\n  MOD((EXTRACT(epoch FROM receive_time) + \r\n    CASE \r\n      WHEN rtcm_msg_type = 1077 THEN $GPSleapseconds\r\n      WHEN rtcm_msg_type = 1087 THEN $GLOleapseconds\r\n      WHEN rtcm_msg_type = 1097 THEN $GALleapseconds\r\n      WHEN rtcm_msg_type = 1117 THEN $QZZSleapseconds\r\n      WHEN rtcm_msg_type = 1127 THEN $BEIleapseconds\r\n      ELSE $GPSleapseconds\r\n    END)::NUMERIC(15,3),86400) - MOD((EXTRACT(epoch FROM rtcm_obs_epoch)),86400) as value\r\nFROM rtcm_packages\r\nWHERE\r\n  $__timeFilter(receive_time) AND\r\n  rtcm_obs_epoch IS NOT NULL AND\r\n  rtcm_sat_count != 0\r\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Max latency last 1 hour [All cons]",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 69 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  MAX(receive_time) AS time,\r\n  mountpoint AS metric,\r\n  MAX(MOD((EXTRACT(epoch FROM receive_time) + \r\n    CASE \r\n      WHEN rtcm_msg_type = 1077 THEN $GPSleapseconds\r\n      WHEN rtcm_msg_type = 1087 THEN $GLOleapseconds\r\n      WHEN rtcm_msg_type = 1097 THEN $GALleapseconds\r\n      WHEN rtcm_msg_type = 1117 THEN $QZZSleapseconds\r\n      WHEN rtcm_msg_type = 1127 THEN $BEIleapseconds\r\n      ELSE $GPSleapseconds\r\n    END)::NUMERIC(15,3),86400) - MOD((EXTRACT(epoch FROM rtcm_obs_epoch)),86400)) as max_latency\r\nFROM rtcm_packages\r\nWHERE\r\n  receive_time >= NOW() - INTERVAL '60 minutes' AND\r\n  rtcm_obs_epoch IS NOT NULL AND\r\n  rtcm_sat_count != 0\r\nGROUP BY metric\r\nORDER BY time ASC"
    }
   ]
  },
  {
   "title": "minimum latency last 1 hour [all cons]",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 69 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  MAX(receive_time) AS time,\r\n  mountpoint AS metric,\r\n  MIN(MOD((EXTRACT(epoch FROM receive_time) + \r\n    CASE \r\n      WHEN rtcm_msg_type = 1077 THEN $GPSleapseconds\r\n      WHEN rtcm_msg_type = 1087 THEN $GLOleapseconds\r\n      WHEN rtcm_msg_type = 1097 THEN $GALleapseconds\r\n      WHEN rtcm_msg_type = 1117 THEN $QZZSleapseconds\r\n      WHEN rtcm_msg_type = 1127 THEN $BEIleapseconds\r\n      ELSE $GPSleapseconds\r\n    END)::NUMERIC(15,3),86400) - MOD((EXTRACT(epoch FROM rtcm_obs_epoch)),86400)) as max_latency\r\nFROM rtcm_packages\r\nWHERE\r\n  receive_time >= NOW() - INTERVAL '60 minutes' AND\r\n  rtcm_obs_epoch IS NOT NULL AND\r\n  rtcm_sat_count != 0\r\nGROUP BY metric\r\nORDER BY time ASC"
    }
   ]
  }
 ]
}