{
 "title": "Disturbances",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "selected_mountpoint",
    "label": "Mountpoint",
    "query": "SELECT sc.mountpoint\nFROM sourcetable_constants sc\nWHERE mountpoint IN (SELECT DISTINCT mountpoint FROM rtcm_packages)"
   },
   {
    "name": "signals_gps",
    "query": "SELECT DISTINCT sat_signal\nFROM gps_observations where mountpoint = '$selected_mountpoint' AND $__timeFilter(obs_epoch) ORDER BY sat_signal"
   },
   {
    "name": "signals_gal",
    "query": "SELECT DISTINCT sat_signal\nFROM galileo_observations where mountpoint = '$selected_mountpoint' AND $__timeFilter(obs_epoch) ORDER BY sat_signal"
   },
   {
    "name": "signals_glo",
    "query": "SELECT DISTINCT sat_signal\nFROM glonass_observations where mountpoint = '$selected_mountpoint' AND $__timeFilter(obs_epoch) ORDER BY sat_signal"
   },
   {
    "name": "signals_bds",
    "query": "SELECT DISTINCT sat_signal\nFROM bds_observations where mountpoint = '$selected_mountpoint' AND $__timeFilter(obs_epoch) ORDER BY sat_signal"
   }
  ]
 },
 "panels": [
  { "title": "Average Signal to Noise", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "GPS SNR",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroupAlias(obs_epoch,$__interval),\r\nAVG(CASE WHEN sat_signal = 'L1C' then obs_snr END) AS \"L1C\",\r\nAVG(CASE WHEN sat_signal = 'L1P' then obs_snr END) AS \"L1P\",\r\nAVG(CASE WHEN sat_signal = 'L1W' then obs_snr END) AS \"L1W\",\r\nAVG(CASE WHEN sat_signal = 'L1S' then obs_snr END) AS \"L1S\",\r\nAVG(CASE WHEN sat_signal = 'L1L' then obs_snr END) AS \"L1L\",\r\nAVG(CASE WHEN sat_signal = 'L1X' then obs_snr END) AS \"L1X\"\r\n,\r\nAVG(CASE WHEN sat_signal = 'L2C' then obs_snr END) AS \"L2C\",\r\nAVG(CASE WHEN sat_signal = 'L2P' then obs_snr END) AS \"L2P\",\r\nAVG(CASE WHEN sat_signal = 'L2W' then obs_snr END) AS \"L2W\",\r\nAVG(CASE WHEN sat_signal = 'L2S' then obs_snr END) AS \"L2S\",\r\nAVG(CASE WHEN sat_signal = 'L2L' then obs_snr END) AS \"L2L\",\r\nAVG(CASE WHEN sat_signal = 'L2X' then obs_snr END) AS \"L2X\"\r\n,\r\nAVG(CASE WHEN sat_signal = 'L5I' then obs_snr END) AS \"L5I\",\r\nAVG(CASE WHEN sat_signal = 'L5Q' then obs_snr END) AS \"L5Q\",\r\nAVG(CASE WHEN sat_signal = 'L5X' then obs_snr END) AS \"L5X\"\r\nFROM gps_observations where mountpoint = '$selected_mountpoint' AND $__timeFilter(obs_epoch) group by 1"
    }
   ]
  },
  {
   "title": "Glonass SNR",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroupAlias(obs_epoch,$__interval),\r\nAVG(CASE WHEN sat_signal = 'G1C' then obs_snr END) AS \"G1C\",\r\nAVG(CASE WHEN sat_signal = 'G1P' then obs_snr END) AS \"G1P\",\r\nAVG(CASE WHEN sat_signal = 'G2C' then obs_snr END) AS \"G2C\",\r\nAVG(CASE WHEN sat_signal = 'G2P' then obs_snr END) AS \"G2P\"\r\nFROM glonass_observations where mountpoint = '$selected_mountpoint' AND $__timeFilter(obs_epoch) group by 1"
    }
   ]
  },
  {
   "title": "Galileo SNR",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroupAlias(obs_epoch,$__interval),\r\nAVG(CASE WHEN sat_signal = 'E1C' then obs_snr END) AS \"E1C\",\r\nAVG(CASE WHEN sat_signal = 'E1A' then obs_snr END) AS \"E1A\",\r\nAVG(CASE WHEN sat_signal = 'E1B' then obs_snr END) AS \"E1B\",\r\nAVG(CASE WHEN sat_signal = 'E1X' then obs_snr END) AS \"E1X\",\r\nAVG(CASE WHEN sat_signal = 'E1Z' then obs_snr END) AS \"E1Z\",\r\n\r\nAVG(CASE WHEN sat_signal = 'E6C' then obs_snr END) AS \"E6C\",\r\nAVG(CASE WHEN sat_signal = 'E6A' then obs_snr END) AS \"E6A\",\r\nAVG(CASE WHEN sat_signal = 'E6B' then obs_snr END) AS \"E6B\",\r\nAVG(CASE WHEN sat_signal = 'E6X' then obs_snr END) AS \"E6X\",\r\nAVG(CASE WHEN sat_signal = 'E6Z' then obs_snr END) AS \"E6Z\",\r\n\r\nAVG(CASE WHEN sat_signal = 'E7I' then obs_snr END) AS \"E7I\",\r\nAVG(CASE WHEN sat_signal = 'E7Q' then obs_snr END) AS \"E7Q\",\r\nAVG(CASE WHEN sat_signal = 'E7X' then obs_snr END) AS \"E7X\",\r\n\r\nAVG(CASE WHEN sat_signal = 'E8I' then obs_snr END) AS \"E8I\",\r\nAVG(CASE WHEN sat_signal = 'E8Q' then obs_snr END) AS \"E8Q\",\r\nAVG(CASE WHEN sat_signal = 'E8X' then obs_snr END) AS \"E8X\",\r\n\r\nAVG(CASE WHEN sat_signal = 'E5I' then obs_snr END) AS \"E5I\",\r\nAVG(CASE WHEN sat_signal = 'E5Q' then obs_snr END) AS \"E5Q\",\r\nAVG(CASE WHEN sat_signal = 'E5X' then obs_snr END) AS \"E5X\"\r\nFROM galileo_observations where mountpoint = '$selected_mountpoint' AND $__timeFilter(obs_epoch) group by 1"
    }
   ]
  },
  {
   "title": "Beidou SNR",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroupAlias(obs_epoch,$__interval), \r\nAVG(CASE WHEN sat_signal = 'B2I' then obs_snr END) AS \"B2I\",\r\nAVG(CASE WHEN sat_signal = 'B2Q' then obs_snr END) AS \"B2Q\",\r\nAVG(CASE WHEN sat_signal = 'B2X' then obs_snr END) AS \"B2X\",\r\n\r\nAVG(CASE WHEN sat_signal = 'B6I' then obs_snr END) AS \"B6I\",\r\nAVG(CASE WHEN sat_signal = 'B6Q' then obs_snr END) AS \"B6Q\",\r\nAVG(CASE WHEN sat_signal = 'B6X' then obs_snr END) AS \"B6X\",\r\n\r\nAVG(CASE WHEN sat_signal = 'B7I' then obs_snr END) AS \"B7I\",\r\nAVG(CASE WHEN sat_signal = 'B7Q' then obs_snr END) AS \"B7Q\",\r\nAVG(CASE WHEN sat_signal = 'B7X' then obs_snr END) AS \"B7X\",\r\n\r\nAVG(CASE WHEN sat_signal = 'B5D' then obs_snr END) AS \"B5D\",\r\nAVG(CASE WHEN sat_signal = 'B5P' then obs_snr END) AS \"B5P\",\r\nAVG(CASE WHEN sat_signal = 'B5X' then obs_snr END) AS \"B5X\",\r\nAVG(CASE WHEN sat_signal = 'B7D' then obs_snr END) AS \"B7D\",\r\n\r\nAVG(CASE WHEN sat_signal = 'B1D' then obs_snr END) AS \"B1D\",\r\nAVG(CASE WHEN sat_signal = 'B1P' then obs_snr END) AS \"B1P\",\r\nAVG(CASE WHEN sat_signal = 'B1X' then obs_snr END) AS \"B1X\"\r\nFROM beidou_observations where mountpoint = '$selected_mountpoint' AND $__timeFilter(obs_epoch) group by 1"
    }
   ]
  }
 ]
}
{
 "title": "RTCM overview",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "GPSleapseconds", "query": "18" },
   { "name": "GALleapseconds", "query": "18" },
   { "name": "GLOleapseconds", "query": "0" },
   { "name": "BEIleapseconds", "query": "4" },
   {
    "name": "countries",
    "label": "Countries",
    "query": "SELECT DISTINCT countrycode\nFROM sourcetable_constants"
   },
   {
    "name": "casters",
    "label": "Casters",
    "query": "SELECT DISTINCT casterprovider FROM sourcetable_constants"
   },
   {
    "name": "mountpoints",
    "label": "Mountpoints",
    "query": "SELECT sc.mountpoint\nFROM sourcetable_constants sc\nWHERE mountpoint IN (SELECT DISTINCT mountpoint FROM rtcm_packages)\nAND sc.casterprovider in ($casters)\nAND sc.countrycode in ($countries)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Satellite count average",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT rtcm.mountpoint,\r\n  AVG(gps_sum) AS \"GPS\",\r\n  AVG(glo_sum) AS \"GLONASS\",\r\n  AVG(gal_sum) AS \"GALILEO\",\r\n  AVG(bds_sum) AS \"BEIDOU\"\r\nFROM (\r\n  SELECT\r\n    mountpoint,\r\n    $__timeGroup(receive_time, $__interval) as time,\r\n    SUM(CASE WHEN rtcm_msg_type BETWEEN 1071 AND 1077 THEN rtcm_sat_count END)/CAST($__interval_ms/1000 AS INT) AS gps_sum,\r\n    SUM(CASE WHEN rtcm_msg_type BETWEEN 1081 AND 1087 THEN rtcm_sat_count END)/CAST($__interval_ms/1000 AS INT) AS glo_sum,\r\n    SUM(CASE WHEN rtcm_msg_type BETWEEN 1091 AND 1097 THEN rtcm_sat_count END)/CAST($__interval_ms/1000 AS INT) AS gal_sum,\r\n    SUM(CASE WHEN rtcm_msg_type BETWEEN 1121 AND 1127 THEN rtcm_sat_count END)/CAST($__interval_ms/1000 AS INT) AS bds_sum\r\n  FROM rtcm_packages\r\n  WHERE\r\n    $__timeFilter(receive_time) AND mountpoint IN ($mountpoints)\r\n  GROUP BY mountpoint, time\r\n) rtcm\r\nINNER JOIN sourcetable_constants source ON rtcm.mountpoint = source.mountpoint\r\nGROUP BY source.casterprovider, rtcm.mountpoint\r\nORDER BY source.casterprovider, rtcm.mountpoint\r\n"
    }
   ]
  },
  {
   "title": "Satellite count $__interval-average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(receive_time,$__interval),\n  mountpoint AS metric,\n  SUM(rtcm_sat_count)/($__interval_ms/1000) AS \"rtcm_sat_count\"\nFROM rtcm_packages\nWHERE\n $__timeFilter(receive_time) AND (\n  rtcm_msg_type BETWEEN 1071 AND 1077 OR\n  rtcm_msg_type BETWEEN 1081 AND 1087 OR\n  rtcm_msg_type BETWEEN 1091 AND 1097 OR\n  rtcm_msg_type BETWEEN 1121 AND 1127)\n  AND mountpoint IN ($mountpoints)\nGROUP BY time,metric \nORDER BY time,metric "
    }
   ]
  },
  {
   "title": "Mountpoint location from source table",
   "type": "geomap",
   "gridPos": { "h": 24, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT rp.mountpoint, latitude, longitude\r\nFROM sourcetable_constants sc\r\nJOIN (SELECT DISTINCT mountpoint FROM rtcm_packages WHERE $__timeFilter(receive_time)) rp ON rp.mountpoint = sc.mountpoint\r\nWHERE rp.mountpoint IN ($mountpoints)"
    }
   ]
  },
  {
   "title": "Data flow average [kB/s]",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT subquery.mountpoint as metric,\r\n  AVG(count_per_interval)/8/1024 AS \"kB/s average\"\r\nFROM (\r\n  SELECT\r\n    mountpoint,\r\n    $__timeGroup(receive_time, $__interval) as minute,\r\n    SUM(rtcm_msg_size)/CAST($__interval_ms/1000 AS FLOAT) AS count_per_interval\r\n  FROM rtcm_packages\r\n  WHERE\r\n    $__timeFilter(receive_time) AND mountpoint IN ($mountpoints)\r\n  GROUP BY mountpoint, minute\r\n) subquery\r\nINNER JOIN sourcetable_constants source ON subquery.mountpoint = source.mountpoint\r\nGROUP BY source.casterprovider, subquery.mountpoint\r\nORDER BY source.casterprovider, subquery.mountpoint\r\n\r\n"
    }
   ]
  },
  {
   "title": "Data flow $__interval-average [kB/s]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(receive_time,$__interval),\n  mountpoint AS metric,\n  SUM(rtcm_msg_size)/CAST($__interval_ms/1000 AS FLOAT)/8/1024 AS \"kB/s average over $__interval\"\nFROM rtcm_packages \nWHERE\n  $__timeFilter(receive_time) AND mountpoint IN ($mountpoints)\nGROUP BY 1,2 \nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Disconnected mountpoints",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  mountpoint as \"Mountpoint\",\r\n  disconnect_time as \"Disconnected at\",\r\n  reconnect_time as \"Reconnected at\",\r\n  to_char(coalesce(reconnect_time, CURRENT_TIMESTAMP)-disconnect_time, 'HH24:MI:SS') as \"Duration\"\r\nFROM connection_logger\r\nWHERE\r\n  mountpoint IN ($mountpoints) AND (\r\n    $__timeFilter(disconnect_time) OR\r\n    $__timeFilter(reconnect_time) OR\r\n    reconnect_time IS NULL)\r\nORDER BY disconnect_time DESC"
    }
   ]
  },
  {
   "title": "Coordinates [m]",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT coord.mountpoint as \"Mountpoint\", source.casterprovider as \"Caster\", coord.ecef_x as \"X\", coord.ecef_y as \"Y\", coord.ecef_z as \"Z\", coord.anthgt as \"Antenna height\"\r\nFROM coordinates coord\r\nINNER JOIN rtcm_packages rtcm ON coord.rtcm_package_id = rtcm.rtcm_package_id\r\nINNER JOIN sourcetable_constants source ON coord.mountpoint = source.mountpoint\r\nWHERE coord.mountpoint IN ($mountpoints)\r\nORDER BY source.casterprovider, coord.mountpoint"
    }
   ]
  },
  {
   "title": "Data gaps in units of $__interval",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroupAlias(receive_time,$__interval),\r\n  mountpoint AS metric,\r\n  COUNT(rtcm_obs_epoch) AS \"epoch_obs\"\r\nFROM rtcm_packages\r\nWHERE\r\n  mountpoint IN ($mountpoints) AND\r\n  $__timeFilter(receive_time) AND (\r\n  rtcm_msg_type BETWEEN 1071 AND 1077 OR\r\n  rtcm_msg_type BETWEEN 1081 AND 1087 OR\r\n  rtcm_msg_type BETWEEN 1091 AND 1097 OR\r\n  rtcm_msg_type BETWEEN 1121 AND 1127) AND\r\n  rtcm_obs_epoch IS NOT NULL and\r\n  rtcm_sat_count != 0\r\nGROUP BY 1,2\r\nORDER BY 1,2"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Latency of MSM $__interval-average [s]",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroup(receive_time, $__interval) AS time,\r\n  mountpoint AS metric,\r\n  AVG(MOD((EXTRACT(epoch FROM receive_time) + \r\n    CASE \r\n      WHEN rtcm_msg_type BETWEEN 1071 AND 1077 THEN $GPSleapseconds\r\n      WHEN rtcm_msg_type BETWEEN 1081 AND 1087 THEN $GLOleapseconds\r\n      WHEN rtcm_msg_type BETWEEN 1091 AND 1097 THEN $GALleapseconds\r\n      WHEN rtcm_msg_type BETWEEN 1121 AND 1127 THEN $BEIleapseconds\r\n    END)::NUMERIC(15,3),86400) - MOD((EXTRACT(epoch FROM rtcm_obs_epoch)),86400)) as value\r\nFROM rtcm_packages\r\nWHERE\r\n  mountpoint IN ($mountpoints) AND\r\n  $__timeFilter(receive_time) AND\r\n  rtcm_obs_epoch IS NOT NULL AND\r\n  rtcm_sat_count != 0 AND (\r\n  rtcm_msg_type BETWEEN 1071 AND 1077 OR\r\n  rtcm_msg_type BETWEEN 1081 AND 1087 OR\r\n  rtcm_msg_type BETWEEN 1091 AND 1097 OR\r\n  rtcm_msg_type BETWEEN 1121 AND 1127)\r\nGROUP BY 1,2\r\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Maximum latency of MSM [s]",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  MAX(receive_time) AS time,\r\n  mountpoint AS metric,\r\n  MAX(MOD((EXTRACT(epoch FROM receive_time) + \r\n    CASE \r\n      WHEN rtcm_msg_type BETWEEN 1071 AND 1077 THEN $GPSleapseconds\r\n      WHEN rtcm_msg_type BETWEEN 1081 AND 1087 THEN $GLOleapseconds\r\n      WHEN rtcm_msg_type BETWEEN 1091 AND 1097 THEN $GALleapseconds\r\n      WHEN rtcm_msg_type BETWEEN 1121 AND 1127 THEN $BEIleapseconds\r\n    END)::NUMERIC(15,3),86400) - MOD((EXTRACT(epoch FROM rtcm_obs_epoch)),86400)) as max_latency\r\nFROM rtcm_packages\r\nWHERE\r\n  mountpoint IN ($mountpoints) AND\r\n  $__timeFilter(receive_time) AND\r\n  rtcm_obs_epoch IS NOT NULL AND\r\n  rtcm_sat_count != 0 AND (\r\n  rtcm_msg_type BETWEEN 1071 AND 1077 OR\r\n  rtcm_msg_type BETWEEN 1081 AND 1087 OR\r\n  rtcm_msg_type BETWEEN 1091 AND 1097 OR\r\n  rtcm_msg_type BETWEEN 1121 AND 1127)\r\nGROUP BY metric\r\nORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Minimum latency of MSM [s]",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  MAX(receive_time) AS time,\r\n  mountpoint AS metric,\r\n  MIN(MOD((EXTRACT(epoch FROM receive_time) + \r\n    CASE \r\n      WHEN rtcm_msg_type BETWEEN 1071 AND 1077 THEN $GPSleapseconds\r\n      WHEN rtcm_msg_type BETWEEN 1081 AND 1087 THEN $GLOleapseconds\r\n      WHEN rtcm_msg_type BETWEEN 1091 AND 1097 THEN $GALleapseconds\r\n      WHEN rtcm_msg_type BETWEEN 1121 AND 1127 THEN $BEIleapseconds\r\n    END)::NUMERIC(15,3),86400) - MOD((EXTRACT(epoch FROM rtcm_obs_epoch)),86400)) as max_latency\r\nFROM rtcm_packages\r\nWHERE\r\n  mountpoint IN ($mountpoints) AND\r\n  $__timeFilter(receive_time) AND\r\n  rtcm_obs_epoch IS NOT NULL AND\r\n  rtcm_sat_count != 0 AND (\r\n  rtcm_msg_type BETWEEN 1071 AND 1077 OR\r\n  rtcm_msg_type BETWEEN 1081 AND 1087 OR\r\n  rtcm_msg_type BETWEEN 1091 AND 1097 OR\r\n  rtcm_msg_type BETWEEN 1121 AND 1127)\r\nGROUP BY metric\r\nORDER BY time ASC"
    }
   ]
  }
 ]
}